
image: Visual Studio 2022

test_script:
#- ps: Get-Service 'MSSQL$SQL2017'
#- ps: Get-Service 'MSSQL$SQL2019'
#- ps: Get-Service 'MSSQL$SQL2022'

#- ps: Start-Service 'MSSQL$SQL2019'

#- ps: Get-Service 'MSSQL$SQL2017'
#- ps: Get-Service 'MSSQL$SQL2019'
#- ps: Get-Service 'MSSQL$SQL2022'
- ps: Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1"
- ps: ./dotnet-install.ps1 -Channel LTS
build: off
