
image: Previous Visual Studio 2019
#image: vs2019-master-gce-us-central1
#build_cloud: bakery-gce-us-central1
#build_cloud: gce

environment:
  CC:         C:/msys64/mingw64/bin/gcc.exe
  CXX:        C:/msys64/mingw64/bin/g++.exe

init:

- ps: $env:APPVEYOR_BUILD_WORKER_IMAGE
- ps: $env:APPVEYOR_BUILD_WORKER_CLOUD
#- ps: echo $env:APPVEYOR_JOB_ID
#- ps: $PsVersionTable
#- ps: Get-module PowerShellGet -ListAvailable
#- call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars32.bat"
- ps: uname -a
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


install:
  - ps: Copy-Item -Path "CmakeLists.txt" -Destination "C:/msys64/home/appveyor"
  - ps: C:\msys64\usr\bin\bash.exe -lc "cat /etc/os-release"
  - ps: C:\msys64\usr\bin\bash.exe -lc "pacman -Q msys2-runtime"

  - ps: C:\msys64\mingw64\bin\gcc.exe --version
  - ps: C:\msys64\mingw64\bin\g++.exe --version
  #- ps: ./install_cmake.ps1
  
  - ps: ./install_msys.ps1
  - ps: uname -a
  - ps: $env:PATH += ";C:/msys64/mingw64/bin"
  - ps: C:\msys64\usr\bin\bash.exe -lc "cat /etc/os-release"
  - ps: C:\msys64\usr\bin\bash.exe -lc "pacman -Q msys2-runtime"
  - ps: C:\msys64\mingw64\bin\gcc.exe --version
  - ps: C:\msys64\mingw64\bin\g++.exe --version
  - ps: C:\OpenSSL-Win64\bin\openssl version
  - ps: C:\msys64\usr\bin\bash.exe -lc "cmake -B./build -G 'Ninja' -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo"

  #- ps: Get-ChildItem -Path "C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt\"
  #- ps: Get-ChildItem -Path "C:\msys64\mingw64\lib"
  #- ps: Get-ChildItem -Path "C:\msys64\mingw32\lib"
  #- ps: Get-Command Connect-*
  #- ps: .\cmdlet-test.ps1
  #- ps: .\install_nuget.ps1
  #- gettext --version
  #- ps: "[Net.ServicePointManager]::SecurityProtocol = 'Tls11'"
  #- ps: Start-FileDownload 'https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.13/bin/windows/hdf5-1.8.13-win32-VS2010-shared.zip'
  #- where curl
  #- curl -fsS -o hdf5-1.8.13-win32-VS2010-shared.zip https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.13/bin/windows/hdf5-1.8.13-win32-VS2010-shared.zip
  #- ps: ./ruby_install.ps1
  #- SET PATH=C:\Ruby26\bin;%PATH%
  #- python -m pip install pip==23.2.1
  # - nuget help
  # - dotnet --version
  # - python -m pip --version
  # - python -m pip install wheel
  # - ruby --version
  # - gem --version
  # - bundle --version
  #- bundle install
  #- ridk.cmd exec bundle exec rake compile

 
#build:
#   publish_nuget: true
#   publish_nuget_symbols: true
#   include_nuget_references: true
#   verbosity: minimal
  
# after_build:
#   - appveyor PushArtifact MyNuGetLib.1.0.116.nupkg
  
test_script:
#- ps: dotnet tool install --global foreman --version "0.23.2"
#- ps: ./test.ps1
# - ps: ./upload_tests.ps1
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#- SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%"
- ps: dotnet --list-sdks
#- python --version
#- pwsh.exe -File C:\projects\test-appveyor\test.ps1 -ExecutionPolicy Bypass
#- call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars32.bat"
#- ps: Get-Service 'MSSQL$SQL2017'
#- ps: Get-Service 'MSSQL$SQL2019'
#- ps: Get-Service 'MSSQL$SQL2022'

#- ps: Start-Service 'MSSQL$SQL2019'

#- ps: Get-Service 'MSSQL$SQL2017'
#- ps: Get-Service 'MSSQL$SQL2019'
#- ps: Get-Service 'MSSQL$SQL2022'
#- ps: Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1"
#- ps: ./dotnet-install.ps1 -Channel LTS
#- ps: nuget
build: off
