
configuration:
  - Release

image:
  - Visual Studio 2022

environment:
  NSISDIR: C:\Program Files (x86)\NSIS
  QTDIR: C:\Qt\6.8\msvc2019_64
  OPENSSLDIR: C:\OpenSSL-v33-Win64\bin

install:
- cmd: |-
    set PATH=%QTDIR%\bin;%PATH%
    call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat

build_script:
- cmd: |-
    lrelease --version
    qmake --version
    nmake --version
